apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nexus-pull
spec:
  params:
    - description: The username
      name: user
      type: string
    - description: nexus-password
      name: nexus-password
      type: string
    - description: nexus asset id
      name: asset-id
      type: string
    - name: repo-name
      type: string
    - name: nexus-action
      type: string
    - default: >-
        http://nexus3-mod-resorts.paul-pg-roks-3cd0ec11030dfa215f262137faf739f1-0000.eu-gb.containers.appdomain.cloud/service/rest/v1/components/
      name: url
      type: string
  steps:
    - args:
        - >-
          yum install jq -y

          ls   

          if [ -z $(params.component-id) ]; then 
            echo "Github push"
            curl -u $nexusUser:$nexusPassword -X GET $(params.url)$(cat component_version.txt) --output nexus-assets.json

            else 
            echo "Nexus push"  
            curl -u $nexusUser:$nexusPassword -X GET $(params.url)$(params.component-id) --output nexus-assets.json

          fi

          mkdir target

          echo -- PULLING NEXUS assets --

          jq '.assets[] | .downloadUrl' nexus-assets.json >>
          component-downloads.json

          while IFS= read -r line; do
              THELINE=$(echo $line | tr -d '"')
              FILENAME=$(echo $THELINE | awk -F / '{print$NF}' | tr -d '"')
              echo FILENAME $FILENAME
              THEURL=$(echo $THELINE)
              echo THE_URL $THEURL
              curl -u $nexusUser:$nexusPassword -X GET $THEURL --output $FILENAME 
              cp $FILENAME target
          done < component-downloads.json

          ls
      command:
        - /bin/bash
        - "-c"
      env:
        - name: nexusPassword
          valueFrom:
            secretKeyRef:
              key: nexusPassword
              name: nexus-secrets
              optional: true
        - name: nexusUser
          valueFrom:
            secretKeyRef:
              key: nexusUser
              name: nexus-secrets
              optional: true
      image: "quay.io/openshift/origin-cli:latest"
      name: pull
      resources: {}
      workingDir: /workspace/output
    - args:
        - ls
      command:
        - /bin/bash
        - "-c"
      image: "quay.io/openshift/origin-cli:latest"
      name: build
      resources: {}
      securityContext:
        privileged: true
      workingDir: /workspace/output
  workspaces:
    - name: output
