apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-
spec:
  params:
    - name: user
      value: admin
    - name: nexus-password
      value: password
  pipelineRef:
    name: sars-pipeline
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: sars-pvc
  serviceAccountName: pipeline
  timeout: 1h0m0s
