apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-
spec:
  params:
    - name: docker-image
      value: image-registry.openshift-image-registry.svc:5000/mod-resorts/nexus-mod-resorts:latest
  pipelineRef:
    name: sars-pipeline
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: sars-pvc
  serviceAccountName: pipeline
  timeout: 1h0m0s
