apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: mod-resorts-scm-trigger-template
spec:
  params:
    - default: mod-resorts
      name: image-namespace
    - name: commitId
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-
      spec:
        params:
          - name: docker-image
            value: >-
              image-registry.openshift-image-registry.svc:5000/$(params.image-namespace)/nexus-mod-resorts:$(params.commitId)
        pipelineRef:
          name: sars-pipeline
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: git-source
            persistentVolumeClaim:
              claimName: nexus-mod-resorts-pvc
