apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: nexus-mod-resorts-trigger-binding
spec:
  params:
    - name: assetId
      value: $(body.component.componentId)
    - name: nexusAction
      value: $(body.action)
    - name: repoName
      value: $(body.repositoryName)
